-- 코드를 입력하세요
SELECT first.FLAVOR
FROM FIRST_HALF first
CROSS JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL2 FROM JULY GROUP BY FLAVOR) july
ON first.FLAVOR = july.FLAVOR
ORDER BY (IFNULL(first.TOTAL_ORDER,0) + IFNULL(july.TOTAL2,0)) DESC
LIMIT 3;

